#公共配置
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  #激活哪一个环境的配置文件
  profiles:
    active: dev
  #视图配置
  mvc:
    static-path-pattern: /static/**

  #请求文件的大小限制
  servlet:
    multipart:
      max-request-size: 10M
      max-file-size: 10M
      enabled: true

  #网络请求配置
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  #模板引擎配置
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.######
      template_exception_handler: ignore
    request-context-attribute: rc
    charset: UTF-8
  #连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

  #缓存配置
  cache:
    type: redis
    cache-names: boot-demo

#日志
logging:
  config: classpath:log/logback.xml
  path: /home/log/boot-demo

---
#开发环境配置
server:
  #端口
  port: 8088
spring:
  profiles: dev
  #redis配置
  redis:
    database: 2
    host:
    port: 18300
    password:      # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
  # 数据源配置
  datasource:
    url:
    username:
    password:


#自定义配置属性
#源码生成文件夹
source-code-dic:   /home/log/boot-demo
source-code-zipfile:  /home/log/boot-demo/src.rar



